export const Users = [
    {
      id:1,
      profilePicture: "images/1.jpeg",
      username: "PUMa Roy",
    },
    {
      id:2,
      profilePicture: "images/2.jpeg",
      username: "Hariom",
    },
    {
      id:3,
      profilePicture: "images/3.jpeg",
      username: "KelyaTown",
    },
    {
      id:4,
      profilePicture: "images/4.jpeg",
      username: "Devine Trow",
    },
    {
      id:5,
      profilePicture: "images/5.jpeg",
      username: "Heluma",
    },
    {
      id:6,
      profilePicture: "images/6.jpeg",
      username: "Jai-Ram-Opera",
    },
    {
      id:7,
      profilePicture: "images/7.jpeg",
      username: "Tridev",
    },
    {
      id:8,
      profilePicture: "images/8.jpeg",
      username: "Krishna",
    },
    {
      id:9,
      profilePicture: "images/9.jpeg",
      username: "Roy Mitra",
    },
    {
      id:10,
      profilePicture: "images/10.jpeg",
      username: "Joy",
    },
  ];
  
  export  const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "images/post/env1.png",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "images/post/env2.png",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "images/post/env3.jfif",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "images/post/env4.jfif",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "images/post/env5.jfif",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "images/post/env6.jfif",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "images/post/env7.jfif",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "images/post/env8.jfif",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "images/post/env9.jfif",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "images/post/env10.jfif",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];
  // export {Users};
// export { Posts};